openapi: 3.1.0

info:
  title: Wallet API
  version: "1.0.0"
  description: API for user registration, authentication, deposit, transfer, reverse, and transaction history.

servers:
  - url: http://localhost:8000/api

paths:
  /register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password, password_confirmation]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        '201':
          description: User registered
        '422':
          description: Validation error

  /login:
    post:
      tags:
        - Auth
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authenticated successfully

  /logout:
    post:
      tags:
        - Auth
      summary: Logout the currently authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logged out successfully
        '401':
          description: Unauthorized - missing or invalid token

  /wallet:
    get:
      tags:
        - Wallet
      summary: Get wallet balance
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current wallet balance and user email
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: user@example.com
                  balance:
                    type: number
                    example: 250.00
        '401':
          description: Unauthorized
          
  /deposit:
    post:
      tags:
        - Wallet
      summary: Deposit money
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [amount]
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: Deposit successful
        '422':
          description: Validation error

  /transfer:
    post:
      tags:
        - Wallet
      summary: Transfer money to another user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [to_user_id, amount]
              properties:
                to_user_id:
                  type: integer
                amount:
                  type: number
      responses:
        '200':
          description: Transfer successful
        '400':
          description: Insufficient funds

  /reverse:
    post:
      tags:
        - Wallet
      summary: Reverse a transaction
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [reference]
              properties:
                reference:
                  type: string
      responses:
        '200':
          description: Transaction reversed
        '404':
          description: Transaction not found

  /transactions:
    get:
      tags:
        - Wallet
      summary: List all user transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of transactions
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
